/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.servlet.ServletContext
 *  javax.servlet.ServletException
 *  javax.servlet.http.HttpServletRequest
 *  javax.servlet.http.HttpServletResponse
 */
package com.labvantage.sapphire.pageelements.gwt.server;

import com.labvantage.sapphire.instrument.textparser.GenericTextParser;
import com.labvantage.sapphire.util.json.JSONUtil;
import java.io.PrintWriter;
import java.util.HashMap;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import sapphire.servlet.BaseAjaxRequest;
import sapphire.util.DataSet;

public class TextParsingRequest
extends BaseAjaxRequest {
    public static final HashMap examples = new HashMap();

    @Override
    public void processRequest(HttpServletRequest request, HttpServletResponse response, ServletContext servletContext) throws ServletException {
        PrintWriter out = null;
        try {
            out = response.getWriter();
            String mode = request.getParameter("mode");
            if ("loadexample".equals(mode)) {
                String exampleid = request.getParameter("exampleid");
                out.write((String)examples.get(exampleid));
            } else {
                String text = request.getParameter("text");
                String parsingRule = request.getParameter("parsingrule");
                long t = System.currentTimeMillis();
                DataSet ds = GenericTextParser.parseDataSet(text, parsingRule);
                this.logInfo("$$$Parsing Took:" + (System.currentTimeMillis() - t) + "ms");
                out.write(JSONUtil.toJSONObject(ds).toString());
            }
        }
        catch (Throwable t) {
            out.write("Error:" + t.getMessage());
        }
    }

    static {
        examples.put("Single Line Values Only", "XXX 11.28 23C 2010-JUN-10 11:11 AM|$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[PH]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract number]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Temp]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[before 'C']]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract last 2]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Time]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract date 'yyyy-MMM-dd']]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[PHAbout]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract number '00.0']]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Single Line With Label and Value", "PH 11.2, Temperature 23, Date 2010-JUN-10 11:11 AM|$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[PH]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 3]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 7]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Temp]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 21]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 23]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Date]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 30]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 50]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Multiple Lines", "PH 11.2, Temperature 23.3, Date JUN 10, 2010 11:12 AM\r\nPH 11.4, Temperature 23.1, Date Feb 10, 2010 11:11 AM\r\nPH 11.5, Temperature 22.9, Date Jan 29, 1999 10.00 AM|$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n\t<property id=\"splitby\" type=\"simple\"><![CDATA[line]]></property>\n\t<property id=\"repeat\" type=\"simple\"><![CDATA[Y]]></property>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[PH]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 3]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 7]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Temp]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 21]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 25]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Date]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[line 1 col 32]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[to line 1 col 53]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Delimited Text", "34.5,57.897,77.7e+5,-1.23E-2,12345678|$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n\t<property id=\"splitby\" type=\"simple\"><![CDATA[,]]></property>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Al]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[token 1]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[K]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[token 2]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Na]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[token 3]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Pb]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[token 4]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Ag]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[token 5 extract 4]]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Delimited Text With Embedded Labels", "Cesium 34.5,Francium 57.897,Lithium 77.7e+5,Potassium -1.23E-2,Rubidium 12345678,Sodium 99|$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n\t<property id=\"splitby\" type=\"simple\"><![CDATA[,]]></property>\n\t<property id=\"repeat\" type=\"simple\"><![CDATA[Y]]></property>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[[extract before ' ']]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[after ' ']]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Regex And Rule Chaining", "Analysis Report      Averages             Sun 03-31-96 03:12:38 PM     page 1\n\n \nMethod: VFQT       Sample Name: STD1                  Operator:    \nRun Time: 03/23/96 08:44           Filename: 960324  \nMode: IR           Type: X         Corr. Factor:        1.00000\nLab ID.:           Cust. Smpl. ID.:            Cust. ID.:         \n \n \nElems     V_2924   Na5889   Al3961   Si2881   Fe2599   Ni2316  \nUnits     ppm      ppm      ppm      ppm      ppm      ppm     \nAvge       .01033   .42011   .05311   .10122   .04088   .05566 \nSDev      0        .00287   .00491   .00101   .00126   .00133  \n%RSD      0        .68407   9.25244  1.00605  3.08636  2.39521 \n \nElems     Ca3179   Mg2790   Pb2203   Zn2138   Cu3247           \nUnits     ppm      ppm      ppm      ppm      ppm              \nAvge       .13722   .07311   .01755   .01466   .014            \nSDev      .00038   .0005    .00019   0        0                \n%RSD      .28049   .69644   1.09623  0        0                |$|<propertylist>\n<property id=\"splitrule\" type=\"propertylist\">\n<propertylist>\n</propertylist>\n</property>\n<property id=\"fields\" type=\"collection\">\n<collection><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Sample Name]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[after ': ' after ': ']]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[before ' ']]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract()]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Fe]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract /Fe\\d{4}/ extract last 4]]></property></propertylist><propertylist >\n\t<property id=\"fieldid\" type=\"simple\"><![CDATA[Al]]></property>\n\t\n\t<property id=\"startrule\" type=\"simple\"><![CDATA[after /Na\\d{4}/]]></property>\n\t<property id=\"endrule\" type=\"simple\"><![CDATA[before /Si\\d{4}/]]></property>\n\t<property id=\"extractrule\" type=\"simple\"><![CDATA[extract /\\d{4}/]]></property></propertylist>\n</collection>\n</property>\n</propertylist>");
        examples.put("Analysis Report", "Analysis Report      Averages             Sun 03-31-96 03:12:38 PM     page 1\n\n \nMethod: VFQT       Sample Name: STD1                  Operator:    \nRun Time: 03/23/96 08:44           Filename: 960324  \nMode: IR           Type: X         Corr. Factor:        1.00000\nLab ID.:           Cust. Smpl. ID.:            Cust. ID.:         \n \n \nElems     V_2924   Na5889   Al3961   Si2881   Fe2599   Ni2316  \nUnits     ppm      ppm      ppm      ppm      ppm      ppm     \nAvge       .01033   .42011   .05311   .10122   .04088   .05566 \nSDev      0        .00287   .00491   .00101   .00126   .00133  \n%RSD      0        .68407   9.25244  1.00605  3.08636  2.39521 \n \nElems     Ca3179   Mg2790   Pb2203   Zn2138   Cu3247           \nUnits     ppm      ppm      ppm      ppm      ppm              \nAvge       .13722   .07311   .01755   .01466   .014            \nSDev      .00038   .0005    .00019   0        0                \n%RSD      .28049   .69644   1.09623  0        0                |$|Sample Name=extract all after 'Sample Name: ' before ' ' \nRun Time=extract date 'MM/dd/yy hh:ss' after 'Run Time'\nNa=extract number after 'Elems' after 'Na'\nAl=extract number after 'Al' \nSi=extract number from line 10 after 'Si'\nFe=extract 4 from line 10 after 'Fe'\nNi=extract last number from line 10\nCa=extract /Ca\\d{4}/ extract last 4\nReport Date=extract date 'MM-dd-yy hh:mm:ss a'");
        examples.put("Analysis Report Nested Parsing", "Method: VFQT       Sample Name: STD1                  Operator:    \r\nRun Time: 03/23/96 08:44           Filename: 960324  |$|{\"splitrule\":{\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1},\"__propertylistid\":\"root_0\",\"fields\":[{\"fieldid\":\"Sample Name\",\"startrule\":\"after('Sample Name: ')\",\"endrule\":\"before(' ')\",\"extractrule\":\"extract()\",\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1},{\"fieldid\":\"Data Line\",\"childfield\":{\"splitrule\":{\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1},\"__propertylistid\":\"root_0\",\"fields\":[{\"fieldid\":\"Run Time\",\"startrule\":\"line(2)\",\"endrule\":\"before('324')\",\"extractrule\":\"extractDate('MM/dd/yy hh:ss')\",\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1},{\"fieldid\":\"N2\",\"startrule\":\"after('ame')\",\"endrule\":\"ppp(2)\",\"extractrule\":\"extractNumber()\",\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1}],\"__propertylistsequence\":-1},\"startrule\":\"line(2)\",\"endrule\":\"before('44')\",\"extractrule\":\"extract(3)\",\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1},{\"fieldid\":\"N1\",\"startrule\":\"after('ame')\",\"endrule\":\"after('ame')\",\"extractrule\":\"after('ame')\",\"__propertylistid\":\"root_0\",\"__propertylistsequence\":-1}],\"__propertylistsequence\":-1}");
    }
}

